version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/event_db
    networks:
      - flask-mongo-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - flask-mongo-network

networks:
  flask-mongo-network:
    driver: bridge
